server:
  port: 8080

spring:
  application:
    name: lunch

  datasource:
    url: jdbc:postgresql://3.39.22.193:5432/lunch    # 서버에서는 localhost
    username: postgres
    password: yds#871219
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true