server:
  port: 8080

spring:
  application:
    name: lunch

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hanryangdev@gmail.com
    password: polebcwgssrqpesv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true