server:
  port: 8080

spring:
  application:
    name: lunch

  datasource:
    url: jdbc:postgresql://49.50.136.141:5432/lunch
    username: postgres
    password: yds#871219
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true